name: frontend
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  go_router: ^3.0.4
  hooks_riverpod: ^1.0.3
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: 
  flutter_gen_runner:
  objectbox_generator: 
  freezed: 
  mocktail: ^0.3.0

flutter_gen:
  output: lib/src/core/generated/

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:

    - family: Maruburi
      fonts:
        - asset: assets/fonts/maruburi/MaruBuri-Regular.ttf
        - asset: assets/fonts/maruburi/MaruBuri-Bold.ttf
          weight: 900
        - asset: assets/fonts/maruburi/MaruBuri-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/maruburi/MaruBuri-Light.ttf
          weight: 300
        - asset: assets/fonts/maruburi/MaruBuri-SemiBold.ttf
          weight: 700

    - family: Iropke
      fonts:
        - asset: assets/fonts/iropke/IropkeBatangM.ttf

    - family: NanumBarunPen
      fonts:
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenR.ttf
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenB.ttf
          weight: 700